name: "Setup OPA"
description: Sets up Open Policy Agent CLI in your GitHub Actions workflow.
inputs:
  version:
    description: Version of Open Policy Agent CLI to install. Semver Ranges (https://www.npmjs.com/package/semver#ranges) are supported.
    required: false
    default: latest
  static:
    description: Set to true to use the static binary version. Defaults to false. Not available for Win32
    required: false
    default: 'false'
  github-token:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to get the list of OPA CLI versions. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
  mirror:
    description: Set to the URL of the mirror you should download from. Defaults to https://github.com. Not available for latest or edge versions.
    default: https://github.com
    required: false
runs:
  using: node20
  main: dist/index.js
